### ISSUE TITLE
Found missing inputs in X_df. It should have one row per id and time for the complete forecasting horizon.

### ISSUE THREAD

**Issue by aaron9980** [Nixtla/mlforecast#336] opened 2024-04-17 14:36 UTC
### What happened + What you expected to happen

Hi I'm trying to replicate the M5 forecast-eval notebook code but it gives the error message:
 ValueError: Found missing inputs in X_df. It should have one row per id and time for the complete forecasting horizon.
You can get the expected structure by running `MLForecast.make_future_dataframe(h)` or get the missing combinatins in your current `X_df` by running `MLForecast.get_missing_future(h, X_df)`. I ran the above functions and found that the X_df is correct and the get_missing_future() gives the wrong missing data as there are no missing data and the missing data are past dates. I did not change any of the code from the M5 forecast eval code so I'm confused at what went wrong.

### Versions / Dependencies

mlforecast.__version__  : 0.11.2 
coreforecast vresion : 0.0.3 (Had to install this to avoid error when installing pip install -qqq "mlforecast[lag_transforms]")
Python: 3.9.7
Windows OS (Running on Jupyter Notebook)

### Reproduction script

%%time
fcst.fit(
    long,
    id_col='id',
    time_col='date',
    target_col='y',
    static_features=['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'],
)

%time preds = fcst.predict(28, X_df=X_df)

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment] 2024-04-17 16:14
Hey. I'm able to run the [notebook](https://www.kaggle.com/code/lemuz90/m5-mlforecast-eval) end to end as-is. Are you also using kaggle? If you're not, where are you getting the data from?

> get_missing_future() gives the wrong missing data as there are no missing data and the missing data are past dates

What that does is take the end dates for each id with something like: `long.groupby('id')['date'].max()` and apply the `freq` offset (from the constructor) to build the dates in the forecasting horizon, so if that's producing dates that are in the past it means that your `long` df doesn't have them.

**Comment by aaron9980** [comment] 2024-04-18 08:41
Hi yes I am using kaggle and the data from M5 competition. I ran it from end to end it gave me the same error. The only changes I made are installing coreforecast version 0.0.3 as it kept giving the error ( AttributeError: module 'coreforecast.lag_transforms' has no attribute 'BaseLagTransform') and removing the input path for all loading data functions as my files are located in the same directory as the notebook. I appreciate the reply and I'll look into what went wrong when creating the long data df.

**Comment by aaron9980** [comment] 2024-04-18 10:46
Hi just to add on to something, according to your response if get_missing_future() returns dates in the past it means long_df does not have them. However running this function also gives me missing data from the future, however this future exceeds the number of days I would like to forecast (28). Could you tell me what does this indicates? Considering how the maximum date for forecasting is 2016-06-19.
![Screenshot 2024-04-18 204619](https://github.com/Nixtla/mlforecast/assets/142385819/c1726d5d-9d35-4046-9d15-6e37363e19fc)

![Screenshot 2024-04-18 204423](https://github.com/Nixtla/mlforecast/assets/142385819/df83bed8-60b6-4507-af21-952908df6c53)

**Comment by aaron9980** [comment] 2024-04-18 10:54
Hi according to your reply when get_missing_future() returns a date in a past, it means that long df does not have them. However here from my screenshots the long df contains the dates that get_missing_future() states are missing. Is there a reason for that?
![Screenshot 2024-04-18 205428](https://github.com/Nixtla/mlforecast/assets/142385819/498ac4a7-fe53-4557-a398-ed8212d69d46)

**Comment by aaron9980** [comment] 2024-04-18 14:14
Update: I attempted to do forecasting on one of the 'valid' products and the forecasting work, therefore i think that the issue isnt compatability but instead the problem probably occurred when processing the data. I will attempt to find a fix

**Comment by jmoralez** [comment] 2024-04-18 15:00
We perform a join with the expected and the X_df. Is it possible that the ids in long and X_df have a different type?

**Comment by aaron9980** [comment] 2024-04-18 15:05
Yep they have a different type. The id in long is category while the id in X_df is an object

**Comment by aaron9980** [comment] 2024-04-18 15:52
When I wanted to view the expected output for an apparent missing days for the product HOBBIES_2_132_CA_1_evaluation, the expected future function returns a past date, however my  long_df does have these dates. Is there a reason why this happens? I think this happens to most of the products that are being forecaste. Sorry for the overwhelming questions I appreciate your time.


![image](https://github.com/Nixtla/mlforecast/assets/142385819/9210deb5-15ad-4c42-a3e3-8d1d61e6b6e2)
![image](https://github.com/Nixtla/mlforecast/assets/142385819/f1bfaa65-43e4-4b71-9cb5-38c0c5bb0a4b)

**Comment by jmoralez** [comment] 2024-04-18 16:33
Are you able to share the notebook (either through kaggle or here)? I'm not able to reproduce the problem.

**Comment by aaron9980** [comment] 2024-04-18 16:39
Here it is. Currently I'm on mlforecas version 0.11.2, however I installed it using local file as pip install could not find the older version.
[m5-mlforecast-eval.md](https://github.com/Nixtla/mlforecast/files/15027884/m5-mlforecast-eval.md)

**Comment by aaron9980** [comment] 2024-04-18 16:42
[m5-mlforecast-eval.zip](https://github.com/Nixtla/mlforecast/files/15027923/m5-mlforecast-eval.zip)
Heres the ZIP with the Notebook instead. Currently I'm on mlforecas version 0.11.2, however I installed it using local file as pip install could not find the older version.

**Comment by jmoralez** [comment] 2024-04-18 17:29
I was able to reproduce the issue locally, but it seems to be due to my version of pandas, I was on 1.5.3 and upgrading to 2.2.2 fixed it. Can you try that? I'll still investigate what the source of the problem is for that version.

**Comment by aaron9980** [comment] 2024-04-19 07:13
Hi, your answer solved my problem. I realised I had a way older version where my pandas had a version of 1.3.4. However after I updated it I had too much errors from other packages due to dependencies. Hence I reinstalled anaconda and it solved my issue. I'm curious why the issue occurred though. Anyways thanks for your help even though the issue was easy to fix.

**Comment by jmoralez** [comment] 2024-04-19 18:48
Hey. This should be fixed by https://github.com/Nixtla/utilsforecast/pull/79, so you should be able to use pandas<2 with utilsforecast>=0.1.5.

I'm closing this, feel free to reopen if you encounter this issue again.

**Closed by jmoralez** 2024-04-19 18:48 UTC
Labels: bug

**Comment by wmotkowska-inpost** [comment] 2024-05-20 08:41
Had the same error. Turned out that my weekly data was aggregated to Monday and the model with frequency set to "W" aggregates dates to Sunday, so the input dates for X for fitting did not match. CHanged my input dataframe to be aggregated to SUnday date and everything worked.
